# Generated by Django 5.0.1 on 2024-02-05 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentid',
            old_name='Student_id',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stid', to='vege.studentid'),
        ),
    ]
