# Generated by Django 5.0.1 on 2024-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='receipe_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=1000),
        ),
    ]
